# Generated by Django 5.2.5 on 2025-08-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(help_text="Endpoint de la API", max_length=255),
                ),
                (
                    "status_code",
                    models.IntegerField(help_text="Código de respuesta HTTP"),
                ),
                (
                    "response_time",
                    models.FloatField(help_text="Tiempo de respuesta en segundos"),
                ),
                (
                    "response_size",
                    models.IntegerField(help_text="Tamaño de respuesta en bytes"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp de la llamada"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Mensaje de error si aplica"
                    ),
                ),
            ],
            options={
                "verbose_name": "API Log",
                "verbose_name_plural": "API Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DashboardMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Fecha de las métricas", unique=True),
                ),
                (
                    "total_posts",
                    models.IntegerField(default=0, help_text="Total de posts ese día"),
                ),
                (
                    "active_users",
                    models.IntegerField(
                        default=0, help_text="Usuarios activos ese día"
                    ),
                ),
                (
                    "avg_posts_per_user",
                    models.FloatField(
                        default=0.0, help_text="Promedio posts por usuario"
                    ),
                ),
                (
                    "api_response_time",
                    models.FloatField(
                        default=0.0, help_text="Tiempo de respuesta API en ms"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Dashboard Metric",
                "verbose_name_plural": "Dashboard Metrics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_id",
                    models.IntegerField(help_text="ID del post en la API", unique=True),
                ),
                (
                    "user_id",
                    models.IntegerField(help_text="ID del usuario que creó el post"),
                ),
                (
                    "title",
                    models.CharField(help_text="Título del post", max_length=255),
                ),
                ("body", models.TextField(help_text="Contenido del post")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación en BD"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha de última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(help_text="ID del usuario", unique=True),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, help_text="Nombre del usuario", max_length=100
                    ),
                ),
                (
                    "post_count",
                    models.IntegerField(default=0, help_text="Número total de posts"),
                ),
                (
                    "avg_post_length",
                    models.FloatField(
                        default=0.0, help_text="Promedio de caracteres por post"
                    ),
                ),
                (
                    "first_post_date",
                    models.DateTimeField(
                        blank=True, help_text="Fecha del primer post", null=True
                    ),
                ),
                (
                    "last_post_date",
                    models.DateTimeField(
                        blank=True, help_text="Fecha del último post", null=True
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización de stats"
                    ),
                ),
            ],
            options={
                "verbose_name": "User Statistic",
                "verbose_name_plural": "User Statistics",
                "ordering": ["-post_count"],
            },
        ),
    ]
