# Generated by Django 5.2.5 on 2025-08-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nombre del dashboard", max_length=100),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descripción del dashboard"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Dashboard Model",
                "verbose_name_plural": "Dashboard Models",
                "permissions": [
                    ("index_viewer", "Can show to index view (function-based)")
                ],
            },
        ),
    ]
